### ISSUE TITLE
Form Konfigurator and Usermanagement should only be visible when logged in user is admin

### ISSUE THREAD

**Issue by Bakkenrak** [Bakkenrak/enapptus#8]

**Comment by BorelSigma** [comment]
The functionality is implemented but only uses a dummy user (hardcoded in app.js - always admin) so far. 
1. Is there an API for querying **only** my current user?  
2. I noticed that the members received from GET on api/member do not contain any admin property.  

Any Ideas @Bakkenrak  ? :)

**Comment by Bakkenrak** [comment]
Ad 1: You can call to api/member/{mId}
Ad 2: Admin info is only provided when requested by an admin account. That was a security consideration. 
2 options to deal with it: 
- Output admin info always to everyone
- Assume that the current user is no admin when no admin info is provided to his calls

BUT: The admin status of the current user is actually in the response of the login call ;)

**Comment by BorelSigma** [comment]
1 . Ok, to deal with the current user information it would be best to integrate the login module into the app module. This way i can easily store the user object when returned (security: The source code of the app is always accessible via index.html anyways even when not logged in.)
1. I think there is no need to hide admin info alone but all usermanagement info except own user. This means: A non-admin member can not get any information about other members except about himself by calling api/member/{mId}. The latter query should be validated from server.
